version: '3.8'

services:
  # --- 后端服务 ---
  weather-backend:
    build: ./weather-data-backend
    container_name: weather_backend
    restart: always
    expose:
      - "8000"
    environment:
      - WEATHER_DATA_PATH=/data/2025-06-01T00_00_00_cn_flatted.nc
    volumes:
      # 运行环境 .nc 文件的路径
      - /Users/hqw/code/weather-explorer/weather-data-backend/data:/data

  # --- 前端服务 ---
  weather-frontend:
    build: ./weather-data-frontend
    container_name: weather_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - weather-backend # 确保后端先启动